import React, { createContext, useContext, useState, useEffect } from 'react';
import { Language } from './types';

type LanguageContextType = {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Dictionary for translations
const translations: Record<Language, Record<string, string>> = {
  tr: {
    // General
    "appName": "Vize İzleyici Türkiye",
    "home": "Ana Sayfa",
    "submitApplication": "Başvuru Gönder",
    "reviewEntries": "Başvuruları İncele",
    "discussions": "Tartışmalar",
    "seeAllData": "Tüm Verileri Gör",
    "madeWith": "ile yapıldı",
    
    // Hero
    "hero.title": "Vize Başvuru Deneyimlerini Birlikte Takip Ediyoruz",
    "hero.subtitle": "Bu platform, Türk vatandaşlarının yaşadığı vize başvuru süreçlerini ve zaman çizelgelerini belgelemektedir. Ortak deneyimlerimizi paylaşarak, sürece şeffaflık getirmeyi ve adil muamele için savunuculuk yapmayı umuyoruz.",
    "hero.crowdsourced": "Topluluk Verileri",
    "hero.realExperiences": "Gerçek Deneyimler",
    "hero.transparentProcess": "Şeffaf Süreç",
    
    // Dashboard
    "dashboard.title": "Vize Başvuru Panosu",
    "dashboard.allCountries": "Tüm Ülkeler",
    "dashboard.totalApplications": "Toplam Başvuru",
    "dashboard.avgProcessingTime": "Ort. İşlem Süresi",
    "dashboard.approvalRate": "Onay Oranı",
    "dashboard.latestApplication": "Son Başvuru",
    "dashboard.processingTime": "İşlem Süresi",
    "dashboard.processingTimeDesc": "Başvuru gönderiminden pasaport iadesi gününe kadar geçen gün",
    "dashboard.applicationResults": "Başvuru Sonuçları",
    "dashboard.applicationResultsDesc": "Vize başvuru sonuçlarının dağılımı",
    "dashboard.days": "Gün",
    "dashboard.approved": "Onaylandı",
    "dashboard.rejected": "Reddedildi",
    "dashboard.pending": "Beklemede",
    "dashboard.worstCities": "En Uzun Bekleme Süreleri",
    "dashboard.trends": "Son 3 Aydaki Eğilimler",
    "dashboard.financialImpact": "Ekonomik Etki",
    "dashboard.totalAnnualApplications": "Yıllık Toplam Başvuru",
    "dashboard.totalAnnualCost": "Yıllık Toplam Maliyet",
    "dashboard.description": "Başvuru gönderiminden sonuç gününe kadar",
    
    // Recent Applications
    "recentApplications.title": "Son Başvurular",
    "recentApplications.submit": "Deneyiminizi Paylaşın",
    "recentApplications.noApplications": "Henüz başvuru yok",
    "recentApplications.beFirst": "Vize başvuru deneyiminizi paylaşan ilk kişi olun",
    "recentApplications.submitApplication": "Başvuru Gönder",
    "recentApplications.last10": "Son 10 Başvuru",
    
    // Submit Page
    "submit.title": "Vize Deneyiminizi Paylaşın",
    "submit.subtitle": "Vize başvuru deneyiminizi paylaşarak diğer Türk vatandaşlarına yardımcı olun. Katkınız, herkes için süreci daha şeffaf hale getirir.",
    
    // Facts Page
    "facts": "Gerçekler",
    "facts.title": "Vize Gerçekleri",
    "facts.subtitle": "Vize başvuru süreçlerini anlamak için önemli gerçekler, karşılaştırmalar ve gereksinimler",
    "facts.general": "Genel Bilgiler",
    "facts.schengen": "Schengen Bölgesi",
    "facts.comparison": "Karşılaştırmalar",
    "facts.fees": "Vize Ücretleri",
    "facts.visaRequirements": "Vize Gereksinimleri",
    "facts.visaRequirementsDesc": "Umuma mahsus (bordo) pasaportlu Türk vatandaşları için vize gereksinimleri",
    "facts.visaTableCaption": "Türk vatandaşları için vize gereksinimleri",
    "facts.country": "Ülke",
    "facts.requiresVisa": "Vize Gerekli",
    "facts.processingTime": "İşlem Süresi",
    "facts.notes": "Notlar",
    "facts.schengenRules": "Schengen Kuralları",
    "facts.separateApplication": "Ayrı Başvuru",
    "facts.longProcessing": "Uzun İşlem Süresi",
    "facts.electronicVisa": "Elektronik Vize",
    "facts.yes": "Evet",
    "facts.no": "Hayır",
    "facts.days": "gün",
    "facts.schengenFacts": "Schengen Bölgesi Hakkında",
    "facts.schengenFactsDesc": "Schengen bölgesi ve Türk vatandaşları için vize kuralları hakkında bilgiler",
    "facts.schengenMembers": "Schengen Üye Ülkeleri",
    "facts.schengenRule1": "Vize 90/180 gün kuralına tabidir",
    "facts.schengenRule2": "Tek vize ile tüm üye ülkelerde seyahat edilebilir",
    "facts.schengenRule3": "Başvurunun ana hedef ülkeye yapılması gerekir",
    "facts.schengenRule4": "C tipi kısa süreli vize ile çalışma izni verilmez",
    "facts.schengenVisaFree": "Vize Muafiyeti Olan Ülkeler",
    "facts.schengenVisaFreeDesc": "Aşağıdaki ülke vatandaşları Schengen bölgesine vizesiz girebilirler:",
    "facts.comparisonTitle": "Ülke Karşılaştırması",
    "facts.comparisonDesc": "Çeşitli niteliklere sahip olan ülkelerin vize gereksinimlerinin karşılaştırılması",
    "facts.aspect": "Özellik",
    "facts.turkey": "Türkiye",
    "facts.venezuela": "Venezuela",
    "facts.russia": "Rusya",
    "facts.schengenVisa": "Schengen Vizesi",
    "facts.schengenFee": "Schengen Vize Ücreti",
    "facts.ukVisa": "Birleşik Krallık Vizesi",
    "facts.usVisa": "ABD Vizesi",
    "facts.visaFreeCountries": "Vizesiz Ülke Sayısı",
    "facts.required": "Gerekli",
    "facts.notRequired": "Gerekli Değil",
    "facts.keyDifferences": "Önemli Farklar",
    "facts.venezuelaFact": "Venezuela - Schengen Muafiyeti",
    "facts.venezuelaFactDesc": "Venezuela vatandaşları, ekonomik zorluklara rağmen 2015'den beri Schengen bölgesine vizesiz giriş yapabilmektedir.",
    "facts.russiaFact": "Rusya - Ücret Artışı",
    "facts.russiaFactDesc": "Ukrayna'daki savaştan önce Rus vatandaşları 35€ ödüyordu, ancak Şubat 2022'den sonra bu ücret 90€'ya yükseltildi.",
    "facts.turkeyFact": "Türkiye - Standart Ücretlendirme",
    "facts.turkeyFactDesc": "Türk vatandaşları uzun yıllardır standart 90€ vize ücreti ödemektedir ve sıkı belge kontrolleri uygulanmaktadır.",
    "facts.visaFees": "Vize Ücretleri",
    "facts.visaFeesDesc": "Farklı ülkelere başvuru yaparken Türk vatandaşlarının ödediği vize ücretleri",
    "facts.destination": "Hedef",
    "facts.fee": "Ücret",
    "facts.unitedKingdom": "Birleşik Krallık",
    "facts.unitedStates": "Amerika Birleşik Devletleri",
    "facts.canada": "Kanada",
    "facts.australia": "Avustralya",
    "facts.standardFee": "Standart ücret",
    "facts.ukFeeDesc": "Vize tipine göre değişir",
    "facts.usFeeDesc": "Başvuru ücreti, iade edilmez",
    "facts.canadaFeeDesc": "Biyometrik kayıt dahil",
    "facts.australiaFeeDesc": "Elektronik vize ücreti",
    "facts.historicalChanges": "Tarihsel Ücret Değişiklikleri",
    "facts.historicalChangesDesc": "Schengen vize ücretlerinin yıllar içindeki değişimi:",
    "facts.fee2014": "2014: Standart vize ücreti 60€ idi",
    "facts.fee2020": "2020: Ücret 80€'ya yükseltildi",
    "facts.fee2022": "2022: Rusya için ücret 35€'dan 90€'ya yükseltildi",
    "facts.allSchengenCountries": "Tüm Schengen ülkeleri",
    "facts.turkeyRepublic": "Türkiye Cumhuriyeti",
    "facts.idCardTravel": "Kimlik kartı seyahati",
    "facts.noVisaRequired": "Vize gerekli değil",
    "facts.visaOnArrival": "Varışta vize",
    "facts.eVisa": "Elektronik vize",
    "facts.visaAvailableBoth": "Vize hem varışta hem de çevrimiçi olarak mevcuttur",
    "facts.visaRequired": "Vize gerekli",
    "facts.northMacedonia": "Kuzey Makedonya",
    "countries.georgia": "Gürcistan",
    "countries.moldova": "Moldova",
    
    // Form
    "form.detailsTitle": "Başvuru Detayları",
    "form.detailsDescription": "Vize başvurunuzun temel bilgilerini paylaşın",
    "form.country": "Ülke",
    "form.selectCountry": "Ülke seçin",
    "form.countryDescription": "Vize başvurusu yaptığınız ülke",
    "form.city": "Şehir",
    "form.selectCity": "Şehir seçin",
    "form.cityDescription": "Başvuru yaptığınız konsolosluğun / büyükelçiliğin lokasyonu",
    "form.duration": "Ziyaret Süresi (gün)",
    "form.durationPlaceholder": "örn. 12 gün",
    "form.durationDescription": "Vize için talep ettiğiniz gün sayısı",
    "form.purpose": "Ziyaret Amacı",
    "form.selectPurpose": "Ziyaret amacı seçin",
    "form.purposeDescription": "Vize başvurusunun ana amacı",
    "form.submitDate": "Başvuru Tarihi",
    "form.pickDate": "Tarih seçin",
    "form.submitDateDescription": "Başvurduğunuz tarih. Randevu tarihi değil.",
    "form.replyReceived": "Yanıt Alındı",
    "form.replyDateDescription": "Başvurunuzun ilk değerlendirilmesinden sonraki yanıt tarihi (varsa)",
    "form.appointmentDate": "Randevu Tarihi",
    "form.appointmentDateDescription": "Parmak izi ve belge kontrolü için randevu tarihi",
    "form.passportReturned": "Sonuç geldi mi?",
    "form.yes": "Evet",
    "form.no": "Hayır",
    "form.passportReturnedDescription": "Pasaportunuz size geri verildi mi?",
    "form.returnDate": "Pasaport İade Tarihi",
    "form.returnDateDescription": "Pasaportunuzu geri aldığınız tarih",
    "form.resultTitle": "Sonuç Bilgileri",
    "form.resultStatus": "Sonuç Durumu",
    "form.selectResult": "Sonuç seçin",
    "form.resultStatusDescription": "Vize başvurunuzun nihai sonucu",
    "form.validity": "Geçerlilik Süresi",
    "form.validityPlaceholder": "örn. 90 gün, 1 yıl",
    "form.validityDescription": "Vize geçerliliğinin süresi",
    "form.entryType": "Giriş Tipi",
    "form.selectEntryType": "Giriş tipi seçin",
    "form.singleEntry": "Tek Giriş",
    "form.multipleEntry": "Çoklu Giriş",
    "form.entryTypeDescription": "Vizenin tek veya çoklu giriş hakkı sağlayıp sağlamadığı",
    "form.submit": "Gönder",
    "form.submitting": "Gönderiliyor...",
    "form.successMessage": "Başvuru başarıyla kaydedildi",
    "form.successDescription": "Vize deneyiminizi paylaştığınız için teşekkürler",
    "form.errorMessage": "Başvuru gönderilirken bir hata oluştu",
    
    // Footer
    "footer.rights": "Tüm hakları saklıdır.",
    "footer.privacy": "Gizlilik Politikası",
    "footer.terms": "Kullanım Şartları",
    "footer.contact": "İletişim",
    
    // Language Selection
    "language": "Dil",
    "language.turkish": "Türkçe",
    "language.english": "İngilizce",
    "language.german": "Almanca",
    
    // Table
    "table.country": "Ülke",
    "table.city": "Şehir",
    "table.purpose": "Amaç",
    "table.submissionDate": "Başvuru Tarihi",
    "table.appointmentDate": "Randevu Tarihi",
    "table.returnDate": "Dönüş Tarihi",
    "table.processingTime": "İşlem Süresi",
    "table.result": "Sonuç",
    "table.days": "Gün",
    "table.approved": "Onaylandı",
    "table.rejected": "Reddedildi",
    "table.pending": "Beklemede",
    "table.caption": "Son Vize Başvuru Sonuçları",
    
    // Discussions
    "discussions.title": "Vize Tartışmaları",
    "discussions.subtitle": "Vize deneyimlerinizi ve sorularınızı diğer kullanıcılarla paylaşın",
    "discussions.comingSoon": "Tartışma forumu yakında eklenecek",
    "discussions.stayTuned": "Güncellemeler için takipte kalın!",
    
    // Actions
    "actions.title": "Ne Yapabiliriz?",
    "actions.subtitle": "Adil vize politikaları için toplu eylem önerileri",
    "actions.disclaimer.title": "Önemli Not",
    "actions.disclaimer.text": "Aşağıdaki öneriler barışçıl ve yasal değişim yollarıdır. Her zaman yerel yasalara uygun hareket ettiğinizden emin olun.",
    
    "actions.diaspora.title": "Türk Diasporası ile İletişim",
    "actions.diaspora.description": "Yurtdışındaki Türk toplumlarının etkisinden yararlanın",
    "actions.diaspora.point1": "Yerel temsilcileriyle iletişime geçmeleri için yurtdışında yaşayan Türk vatandaşlarıyla iletişime geçin",
    "actions.diaspora.point2": "Türk toplumlarının bulunduğu ülkelerde barışçıl gösteriler düzenleyin",
    "actions.diaspora.point3": "Diaspora örgütleri aracılığıyla imza kampanyaları başlatın",
    
    "actions.tourism.title": "Alternatif Turizm",
    "actions.tourism.description": "Turizm ve iş için alternatif destinasyonları değerlendirin",
    "actions.tourism.point1": "Vizesiz veya daha kolay vize süreçleri olan ülkeleri keşfedin",
    "actions.tourism.point2": "Türk vatandaşlarına adil vize politikaları uygulayan ülkeleri destekleyin",
    "actions.tourism.point3": "Alternatif destinasyonlardan olumlu deneyimleri paylaşın",
    
    "actions.awareness.title": "Farkındalık Yaratın",
    "actions.awareness.description": "Bilgi ve deneyimleri paylaşın",
    "actions.awareness.point1": "Vize ret hikayelerini sosyal medyada belgelendirin ve paylaşın",
    "actions.awareness.point2": "Vize sorunlarını ele almaları için gazeteciler ve medya kuruluşlarıyla iletişime geçin",
    "actions.awareness.point3": "Ailelere ve işletmelere etkisini vurgulayan içerikler oluşturun",
    
    "actions.legal.title": "Hukuki Savunuculuk",
    "actions.legal.description": "Adil muamele için yasal girişimleri destekleyin",
    "actions.legal.point1": "Ayrımcı vize uygulamalarına karşı çıkan organizasyonları destekleyin",
    "actions.legal.point2": "Olası yasal işlemler için haksız muamele vakalarını belgeleyin",
    "actions.legal.point3": "Yasal kanallar aracılığıyla karşılıklı vize politikalarını savunun",
    
    "actions.alternatives.title": "Alternatif Destinasyonlar",
    "actions.alternatives.description": "Türk vatandaşları için daha uygun vize politikaları olan bu ülkeleri değerlendirin:",
    
    "actions.contact.title": "Katılın",
    "actions.contact.description": "Bu girişime katkıda bulunmak ister misiniz? Fikir ve önerileriniz için bizimle iletişime geçin.",
    "actions.contact.email": "Bize e-posta gönderin",

    "countries.germany": "Almanya",
    "countries.france": "Fransa",
    "countries.italy": "İtalya",
    "countries.spain": "İspanya",
    "countries.austria": "Avusturya",
    "countries.belgium": "Belçika",
    "countries.denmark": "Danimarka",
    "countries.finland": "Finlandiya",
    "countries.greece": "Yunanistan",
    "countries.netherlands": "Hollanda",
    "countries.portugal": "Portekiz",
    "countries.sweden": "İsveç",
  },
  en: {
    // General
    "appName": "Visa Tracker Turkey",
    "home": "Home",
    "submitApplication": "Submit Application",
    "reviewEntries": "Review Entries",
    "discussions": "Discussions",
    "seeAllData": "See All Data",
    "madeWith": "made with",
    
    // Hero
    "hero.title": "Tracking Visa Application Experiences Together",
    "hero.subtitle": "This platform documents the visa application process and timelines experienced by Turkish citizens. By sharing our collective experiences, we hope to bring transparency to the process and advocate for fair treatment.",
    "hero.crowdsourced": "Crowdsourced Data",
    "hero.realExperiences": "Real Experiences",
    "hero.transparentProcess": "Transparent Process",
    
    // Dashboard
    "dashboard.title": "Visa Application Dashboard",
    "dashboard.allCountries": "All Countries",
    "dashboard.totalApplications": "Total Applications",
    "dashboard.avgProcessingTime": "Avg. Processing Time",
    "dashboard.approvalRate": "Approval Rate",
    "dashboard.latestApplication": "Latest Application",
    "dashboard.processingTime": "Processing Time",
    "dashboard.processingTimeDesc": "Days from application submission to passport return",
    "dashboard.applicationResults": "Application Results",
    "dashboard.applicationResultsDesc": "Distribution of visa application outcomes",
    "dashboard.days": "Days",
    "dashboard.approved": "Approved",
    "dashboard.rejected": "Rejected",
    "dashboard.pending": "Pending",
    "dashboard.worstCities": "Longest Wait Times",
    "dashboard.trends": "Trends in Last 3 Months",
    "dashboard.financialImpact": "Financial Impact",
    "dashboard.totalAnnualApplications": "Total Annual Applications",
    "dashboard.totalAnnualCost": "Total Annual Cost",
    "dashboard.description": "from submission to result",

    // Recent Applications
    "recentApplications.title": "Recent Applications",
    "recentApplications.submit": "Submit Your Experience",
    "recentApplications.noApplications": "No applications yet",
    "recentApplications.beFirst": "Be the first to share your visa application experience",
    "recentApplications.submitApplication": "Submit Application",
    "recentApplications.last10": "Last 10 Applications",
    
    // Submit Page
    "submit.title": "Share Your Visa Experience",
    "submit.subtitle": "Help other Turkish citizens by sharing your visa application experience. Your contribution makes the process more transparent for everyone.",
    
    // Facts Page
    "facts": "Facts",
    "facts.title": "Visa Facts",
    "facts.subtitle": "Important facts, comparisons, and requirements for understanding visa application processes",
    "facts.general": "General Information",
    "facts.schengen": "Schengen Area",
    "facts.comparison": "Comparisons",
    "facts.fees": "Visa Fees",
    "facts.visaRequirements": "Visa Requirements",
    "facts.visaRequirementsDesc": "Visa requirements for Turkish citizens with an ordinary (burgundy) passport",
    "facts.visaTableCaption": "Visa requirements for Turkish citizens",
    "facts.country": "Country",
    "facts.requiresVisa": "Requires Visa",
    "facts.processingTime": "Processing Time",
    "facts.notes": "Notes",
    "facts.schengenRules": "Schengen Rules Apply",
    "facts.separateApplication": "Separate Application",
    "facts.longProcessing": "Long Processing Time",
    "facts.electronicVisa": "Electronic Visa",
    "facts.yes": "Yes",
    "facts.no": "No",
    "facts.days": "days",
    "facts.schengenFacts": "About Schengen Area",
    "facts.schengenFactsDesc": "Information about the Schengen area and visa rules for Turkish citizens",
    "facts.schengenMembers": "Schengen Member Countries",
    "facts.schengenRule1": "Visa subject to 90/180 day rule",
    "facts.schengenRule2": "One visa allows travel to all member states",
    "facts.schengenRule3": "Application must be made to main destination country",
    "facts.schengenRule4": "No work permit with type C short-stay visa",
    "facts.schengenVisaFree": "Visa-Free Countries",
    "facts.schengenVisaFreeDesc": "Citizens of the following countries can enter the Schengen area without a visa:",
    "facts.comparisonTitle": "Country Comparison",
    "facts.comparisonDesc": "Comparison of visa requirements for countries with various attributes",
    "facts.aspect": "Aspect",
    "facts.turkey": "Turkey",
    "facts.venezuela": "Venezuela",
    "facts.russia": "Russia",
    "facts.schengenVisa": "Schengen Visa",
    "facts.schengenFee": "Schengen Visa Fee",
    "facts.ukVisa": "UK Visa",
    "facts.usVisa": "US Visa",
    "facts.visaFreeCountries": "Visa-Free Countries",
    "facts.required": "Required",
    "facts.notRequired": "Not Required",
    "facts.keyDifferences": "Key Differences",
    "facts.venezuelaFact": "Venezuela - Schengen Exemption",
    "facts.venezuelaFactDesc": "Venezuelan citizens have enjoyed visa-free access to the Schengen area since 2015, despite economic challenges.",
    "facts.russiaFact": "Russia - Fee Increase",
    "facts.russiaFactDesc": "Before the war in Ukraine, Russian citizens paid 35€, but after February 2022, this was increased to 90€.",
    "facts.turkeyFact": "Turkey - Standard Fees",
    "facts.turkeyFactDesc": "Turkish citizens have paid the standard 90€ visa fee for many years with strict document scrutiny.",
    "facts.visaFees": "Visa Fees",
    "facts.visaFeesDesc": "Visa fees paid by Turkish citizens when applying to different countries",
    "facts.destination": "Destination",
    "facts.fee": "Fee",
    "facts.unitedKingdom": "United Kingdom",
    "facts.unitedStates": "United States",
    "facts.canada": "Canada",
    "facts.australia": "Australia",
    "facts.standardFee": "Standard fee",
    "facts.ukFeeDesc": "Varies by visa type",
    "facts.usFeeDesc": "Application fee, non-refundable",
    "facts.canadaFeeDesc": "Includes biometric registration",
    "facts.australiaFeeDesc": "Electronic visa fee",
    "facts.historicalChanges": "Historical Fee Changes",
    "facts.historicalChangesDesc": "Changes in Schengen visa fees over the years:",
    "facts.fee2014": "2014: Standard visa fee was 60€",
    "facts.fee2020": "2020: Fee increased to 80€",
    "facts.fee2022": "2022: Fee for Russians increased from 35€ to 90€",
    "facts.allSchengenCountries": "All Schengen countries",
    "facts.turkeyRepublic": "Republic of Turkey",
    "facts.idCardTravel": "ID card travel",
    "facts.noVisaRequired": "No visa required",
    "facts.visaOnArrival": "Visa on arrival",
    "facts.eVisa": "Electronic visa",
    "facts.visaAvailableBoth": "Visa available both on arrival and online",
    "facts.visaRequired": "Visa required",
    "facts.northMacedonia": "North Macedonia",
    "countries.georgia": "Georgia",
    "countries.moldova": "Moldova",
    
    // Form
    "form.detailsTitle": "Application Details",
    "form.detailsDescription": "Share the basic information about your visa application",
    "form.country": "Country",
    "form.selectCountry": "Select country",
    "form.countryDescription": "The country you applied for a visa to",
    "form.city": "City",
    "form.selectCity": "Select city",
    "form.cityDescription": "The location of the consulate or embassy where you applied",
    "form.duration": "Duration of Visit (days)",
    "form.durationPlaceholder": "e.g. 12 days",
    "form.durationDescription": "Number of days requested for the visa",
    "form.purpose": "Purpose of Visit",
    "form.selectPurpose": "Select purpose",
    "form.purposeDescription": "The main reason for the visa application",
    "form.submitDate": "Submission Date",
    "form.pickDate": "Pick a date",
    "form.submitDateDescription": "Date when all documents and application were submitted",
    "form.replyReceived": "Reply Received",
    "form.replyDateDescription": "Date when you received a reply after the initial assessment (if applicable)",
    "form.appointmentDate": "Appointment Date",
    "form.appointmentDateDescription": "Date of your appointment for fingerprints and document check",
    "form.passportReturned": "Did you get your passport back?",
    "form.yes": "Yes",
    "form.no": "No",
    "form.passportReturnedDescription": "Has your passport been returned to you?",
    "form.returnDate": "Passport Return Date",
    "form.returnDateDescription": "Date when you received your passport back",
    "form.resultTitle": "Result Information",
    "form.resultStatus": "Result Status",
    "form.selectResult": "Select result",
    "form.resultStatusDescription": "The final outcome of your visa application",
    "form.validity": "Validity Period",
    "form.validityPlaceholder": "e.g. 90 days, 1 year",
    "form.validityDescription": "Duration of the visa validity",
    "form.entryType": "Entry Type",
    "form.selectEntryType": "Select entry type",
    "form.singleEntry": "Single Entry",
    "form.multipleEntry": "Multiple Entry",
    "form.entryTypeDescription": "Whether the visa allows single or multiple entries",
    "form.submit": "Submit",
    "form.submitting": "Submitting...",
    "form.successMessage": "Application submitted successfully",
    "form.successDescription": "Thank you for sharing your visa experience",
    "form.errorMessage": "An error occurred while submitting your application",
    
    // Footer
    "footer.rights": "All rights reserved.",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.contact": "Contact",
    
    // Language Selection
    "language": "Language",
    "language.turkish": "Turkish",
    "language.english": "English",
    "language.german": "German",
    
    // Table
    "table.country": "Country",
    "table.city": "City",
    "table.purpose": "Purpose",
    "table.submissionDate": "Submission Date",
    "table.appointmentDate": "Appointment Date",
    "table.returnDate": "Return Date",
    "table.processingTime": "Processing Time",
    "table.result": "Result",
    "table.days": "Days",
    "table.approved": "Approved",
    "table.rejected": "Rejected",
    "table.pending": "Pending",
    "table.caption": "Recent Visa Application Results",
    
    // Discussions
    "discussions.title": "Visa Discussions",
    "discussions.subtitle": "Share your visa experiences and questions with other users",
    "discussions.comingSoon": "Discussion forum coming soon",
    "discussions.stayTuned": "Stay tuned for updates!",
    
    // Actions (English translations)
    "actions.title": "What Can We Do?",
    "actions.subtitle": "Collective actions to advocate for fair visa policies",
    "actions.disclaimer.title": "Important Note",
    "actions.disclaimer.text": "The suggestions below are meant to be peaceful and legal ways to advocate for change. Always ensure your actions comply with local laws.",
    
    "actions.diaspora.title": "Engage with Turkish Diaspora",
    "actions.diaspora.description": "Leverage the influence of Turkish communities abroad",
    "actions.diaspora.point1": "Contact Turkish citizens living abroad to raise awareness with their local representatives",
    "actions.diaspora.point2": "Organize peaceful demonstrations in countries where Turkish communities are present",
    "actions.diaspora.point3": "Create petitions through diaspora organizations",
    
    "actions.tourism.title": "Alternative Tourism",
    "actions.tourism.description": "Consider alternative destinations for tourism and business",
    "actions.tourism.point1": "Explore visa-free countries or those with easier visa processes",
    "actions.tourism.point2": "Support countries that maintain fair visa policies for Turkish citizens",
    "actions.tourism.point3": "Share positive experiences from alternative destinations",
    
    "actions.awareness.title": "Raise Awareness",
    "actions.awareness.description": "Share information and experiences",
    "actions.awareness.point1": "Document and share visa rejection stories on social media",
    "actions.awareness.point2": "Contact journalists and media outlets to cover visa issues",
    "actions.awareness.point3": "Create content highlighting the impact on families and businesses",
    
    "actions.legal.title": "Legal Advocacy",
    "actions.legal.description": "Support legal initiatives for fair treatment",
    "actions.legal.point1": "Support organizations challenging discriminatory visa practices",
    "actions.legal.point2": "Document cases of unfair treatment for potential legal action",
    "actions.legal.point3": "Advocate for reciprocal visa policies through legal channels",
    
    "actions.alternatives.title": "Alternative Destinations",
    "actions.alternatives.description": "Consider these countries with more favorable visa policies for Turkish citizens:",
    
    "actions.contact.title": "Get Involved",
    "actions.contact.description": "Want to contribute to this initiative? Contact us with your ideas and suggestions.",
    "actions.contact.email": "Send us an email",

    "countries.germany": "Germany",
    "countries.france": "France",
    "countries.italy": "Italy",
    "countries.spain": "Spain",
    "countries.austria": "Austria",
    "countries.belgium": "Belgium",
    "countries.denmark": "Denmark",
    "countries.finland": "Finland",
    "countries.greece": "Greece",
    "countries.netherlands": "Netherlands",
    "countries.portugal": "Portugal",
    "countries.sweden": "Sweden",
    "countries.georgia": "Georgia",
    "countries.moldova": "Moldova",
  },
  de: {
    // General
    "appName": "Visum-Tracker Türkei",
    "home": "Startseite",
    "submitApplication": "Antrag einreichen",
    "reviewEntries": "Einträge überprüfen",
    "discussions": "Diskussionen",
    "seeAllData": "Alle Daten sehen",
    "madeWith": "erstellt mit",
    
    // Hero
    "hero.title": "Gemeinsam Visumantrags-Erfahrungen verfolgen",
    "hero.subtitle": "Diese Plattform dokumentiert den Visumantragsprozess und die Zeitpläne, die türkische Staatsbürger erleben. Durch das Teilen unserer gemeinsamen Erfahrungen hoffen wir, Transparenz in den Prozess zu bringen und uns für eine faire Behandlung einzusetzen.",
    "hero.crowdsourced": "Crowdsourced Daten",
    "hero.realExperiences": "Echte Erfahrungen",
    "hero.transparentProcess": "Transparenter Prozess",
    
    // Dashboard
    "dashboard.title": "Visumantrag-Dashboard",
    "dashboard.allCountries": "Alle Länder",
    "dashboard.totalApplications": "Gesamtanträge",
    "dashboard.avgProcessingTime": "Durchschn. Bearbeitungszeit",
    "dashboard.approvalRate": "Genehmigungsrate",
    "dashboard.latestApplication": "Neuester Antrag",
    "dashboard.processingTime": "Bearbeitungszeit",
    "dashboard.processingTimeDesc": "Tage von der Antragseinreichung bis zur Passrückgabe",
    "dashboard.applicationResults": "Antragsergebnisse",
    "dashboard.applicationResultsDesc": "Verteilung der Visumantragsergebnisse",
    "dashboard.days": "Tage",
    "dashboard.approved": "Genehmigt",
    "dashboard.rejected": "Abgelehnt",
    "dashboard.pending": "Ausstehend",
    "dashboard.worstCities": "Längste Wartezeiten",
    "dashboard.trends": "Trends der letzten 3 Monate",
    "dashboard.financialImpact": "Finanzielle Auswirkungen",
    "dashboard.totalAnnualApplications": "Jährliche Gesamtanträge",
    "dashboard.totalAnnualCost": "Jährliche Gesamtkosten",
    "dashboard.description": "von der Einreichung bis zum Ergebnis",
    
    // Recent Applications
    "recentApplications.title": "Neueste Anträge",
    "recentApplications.submit": "Teilen Sie Ihre Erfahrung",
    "recentApplications.noApplications": "Noch keine Anträge",
    "recentApplications.beFirst": "Seien Sie der Erste, der seine Visumantrags-Erfahrung teilt",
    "recentApplications.submitApplication": "Antrag einreichen",
    "recentApplications.last10": "Letzte 10 Anträge",
    
    // Submit Page
    "submit.title": "Teilen Sie Ihre Visum-Erfahrung",
    "submit.subtitle": "Helfen Sie anderen türkischen Staatsbürgern, indem Sie Ihre Visumantrags-Erfahrung teilen. Ihr Beitrag macht den Prozess für alle transparenter.",
    
    // Facts Page
    "facts": "Fakten",
    "facts.title": "Visum-Fakten",
    "facts.subtitle": "Wichtige Fakten, Vergleiche und Anforderungen zum Verständnis von Visumantragsprozessen",
    "facts.general": "Allgemeine Informationen",
    "facts.schengen": "Schengen-Raum",
    "facts.comparison": "Vergleiche",
    "facts.fees": "Visumgebühren",
    "facts.visaRequirements": "Visumanforderungen",
    "facts.visaRequirementsDesc": "Visumanforderungen für türkische Staatsbürger mit einem gewöhnlichen (bordeauxroten) Pass",
    "facts.visaTableCaption": "Visumanforderungen für türkische Staatsbürger",
    "facts.country": "Land",
    "facts.requiresVisa": "Visum erforderlich",
    "facts.processingTime": "Bearbeitungszeit",
    "facts.notes": "Hinweise",
    "facts.schengenRules": "Schengen-Regeln gelten",
    "facts.separateApplication": "Separate Bewerbung",
    "facts.longProcessing": "Lange Bearbeitungszeit",
    "facts.electronicVisa": "Elektronisches Visum",
    "facts.yes": "Ja",
    "facts.no": "Nein",
    "facts.days": "Tage",
    "facts.schengenFacts": "Über den Schengen-Raum",
    "facts.schengenFactsDesc": "Informationen über den Schengen-Raum und Visumregeln für türkische Staatsbürger",
    "facts.schengenMembers": "Schengen-Mitgliedsländer",
    "facts.schengenRule1": "Visum unterliegt der 90/180-Tage-Regel",
    "facts.schengenRule2": "Ein Visum ermöglicht Reisen in alle Mitgliedstaaten",
    "facts.schengenRule3": "Antrag muss an das Hauptzielland gestellt werden",
    "facts.schengenRule4": "Keine Arbeitserlaubnis mit Visum Typ C für Kurzaufenthalte",
    "facts.schengenVisaFree": "Visumfreie Länder",
    "facts.schengenVisaFreeDesc": "Bürger der folgenden Länder können ohne Visum in den Schengen-Raum einreisen:",
    "facts.comparisonTitle": "Ländervergleich",
    "facts.comparisonDesc": "Vergleich der Visumanforderungen für Länder mit verschiedenen Merkmalen",
    "facts.aspect": "Aspekt",
    "facts.turkey": "Türkei",
    "facts.venezuela": "Venezuela",
    "facts.russia": "Russland",
    "facts.schengenVisa": "Schengen-Visum",
    "facts.schengenFee": "Schengen-Visumgebühr",
    "facts.ukVisa": "UK-Visum",
    "facts.usVisa": "US-Visum",
    "facts.visaFreeCountries": "Visumfreie Länder",
    "facts.required": "Erforderlich",
    "facts.notRequired": "Nicht erforderlich",
    "facts.keyDifferences": "Hauptunterschiede",
    "facts.venezuelaFact": "Venezuela - Schengen-Befreiung",
    "facts.venezuelaFactDesc": "Venezolanische Bürger genießen seit 2015 visumfreien Zugang zum Schengen-Raum, trotz wirtschaftlicher Herausforderungen.",
    "facts.russiaFact": "Russland - Gebührenerhöhung",
    "facts.russiaFactDesc": "Vor dem Krieg in der Ukraine zahlten russische Bürger 35€, aber nach Februar 2022 wurde dies auf 90€ erhöht.",
    "facts.turkeyFact": "Türkei - Standardgebühren",
    "facts.turkeyFactDesc": "Türkische Bürger zahlen seit vielen Jahren die Standardgebühr von 90€ für Visa mit strenger Dokumentenprüfung.",
    "facts.visaFees": "Visumgebühren",
    "facts.visaFeesDesc": "Von türkischen Bürgern gezahlte Visumgebühren bei Anträgen für verschiedene Länder",
    "facts.destination": "Ziel",
    "facts.fee": "Gebühr",
    "facts.unitedKingdom": "Vereinigtes Königreich",
    "facts.unitedStates": "Vereinigte Staaten",
    "facts.canada": "Kanada",
    "facts.australia": "Australien",
    "facts.standardFee": "Standardgebühr",
    "facts.ukFeeDesc": "Variiert je nach Visumtyp",
    "facts.usFeeDesc": "Antragsgebühr, nicht erstattungsfähig",
    "facts.canadaFeeDesc": "Inklusive biometrischer Registrierung",
    "facts.australiaFeeDesc": "Elektronische Visumgebühr",
    "facts.historicalChanges": "Historische Gebührenänderungen",
    "facts.historicalChangesDesc": "Änderungen der Schengen-Visumgebühren im Laufe der Jahre:",
    "facts.fee2014": "2014: Standardvisumgebühr betrug 60€",
    "facts.fee2020": "2020: Gebühr erhöht auf 80€",
    "facts.fee2022": "2022: Gebühr für Russen erhöht von 35€ auf 90€",
    "facts.allSchengenCountries": "Alle Schengen-Länder",
    "facts.turkeyRepublic": "Republik Türkei",
    "facts.idCardTravel": "Reise mit Personalausweis",
    "facts.noVisaRequired": "Kein Visum erforderlich",
    "facts.visaOnArrival": "Visum bei Ankunft",
    "facts.eVisa": "Elektronisches Visum",
    "facts.visaAvailableBoth": "Visum sowohl bei Ankunft als auch online verfügbar",
    "facts.visaRequired": "Visum erforderlich",
    "facts.northMacedonia": "Nordmazedonien",
    "countries.georgia": "Georgien",
    "countries.moldova": "Moldawien",
    
    // Form
    "form.detailsTitle": "Antragsdetails",
    "form.detailsDescription": "Teilen Sie die grundlegenden Informationen zu Ihrem Visumantrag",
    "form.country": "Land",
    "form.selectCountry": "Land auswählen",
    "form.countryDescription": "Das Land, für das Sie ein Visum beantragt haben",
    "form.city": "Stadt",
    "form.selectCity": "Stadt auswählen",
    "form.cityDescription": "Der Konsulats-Botschaftsstandort, an dem Sie den Antrag gestellt haben",
    "form.duration": "Besuchsdauer (Tage)",
    "form.durationPlaceholder": "z.B. 12 Tage",
    "form.durationDescription": "Anzahl der Tage die für das Visum beantragt wurden",
    "form.purpose": "Besuchszweck",
    "form.selectPurpose": "Zweck auswählen",
    "form.purposeDescription": "Der Hauptgrund für den Visumantrag",
    "form.submitDate": "Einreichungsdatum",
    "form.pickDate": "Datum auswählen",
    "form.submitDateDescription": "Datum, an dem alle Dokumente und der Antrag eingereicht wurden",
    "form.replyReceived": "Antwort erhalten",
    "form.replyDateDescription": "Datum, an dem Sie nach der ersten Bewertung eine Antwort erhalten haben (falls zutreffend)",
    "form.appointmentDate": "Termindatum",
    "form.appointmentDateDescription": "Datum Ihres Termins für Fingerabdrücke und Dokumentenprüfung",
    "form.passportReturned": "Haben Sie Ihren Pass zurückbekommen?",
    "form.yes": "Ja",
    "form.no": "Nein",
    "form.passportReturnedDescription": "Wurde Ihr Pass an Sie zurückgegeben?",
    "form.returnDate": "Passrückgabedatum",
    "form.returnDateDescription": "Datum, an dem Sie Ihren Pass zurückerhalten haben",
    "form.resultTitle": "Ergebnisinformationen",
    "form.resultStatus": "Ergebnisstatus",
    "form.selectResult": "Ergebnis auswählen",
    "form.resultStatusDescription": "Das endgültige Ergebnis Ihres Visumantrags",
    "form.validity": "Gültigkeitszeitraum",
    "form.validityPlaceholder": "z.B. 90 Tage, 1 Jahr",
    "form.validityDescription": "Dauer der Visumgültigkeit",
    "form.entryType": "Einreisetyp",
    "form.selectEntryType": "Einreisetyp auswählen",
    "form.singleEntry": "Einmalige Einreise",
    "form.multipleEntry": "Mehrfache Einreise",
    "form.entryTypeDescription": "Ob das Visum einmalige oder mehrfache Einreisen ermöglicht",
    "form.submit": "Einreichen",
    "form.submitting": "Wird eingereicht...",
    "form.successMessage": "Antrag erfolgreich eingereicht",
    "form.successDescription": "Vielen Dank für das Teilen Ihrer Visumerfahrung",
    "form.errorMessage": "Beim Einreichen Ihres Antrags ist ein Fehler aufgetreten",
    
    // Footer
    "footer.rights": "Alle Rechte vorbehalten.",
    "footer.privacy": "Datenschutzrichtlinie",
    "footer.terms": "Nutzungsbedingungen",
    "footer.contact": "Kontakt",
    
    // Language Selection
    "language": "Sprache",
    "language.turkish": "Türkisch",
    "language.english": "Englisch",
    "language.german": "Deutsch",
    
    // Table
    "table.country": "Land",
    "table.city": "Stadt",
    "table.purpose": "Zweck",
    "table.submissionDate": "Einreichungsdatum",
    "table.appointmentDate": "Termindatum",
    "table.returnDate": "Rückgabedatum",
    "table.processingTime": "Bearbeitungszeit",
    "table.result": "Ergebnis",
    "table.days": "Tage",
    "table.approved": "Genehmigt",
    "table.rejected": "Abgelehnt",
    "table.pending": "Ausstehend",
    "table.caption": "Aktuelle Visumantrags-Ergebnisse",
    
    // Discussions
    "discussions.title": "Visum-Diskussionen",
    "discussions.subtitle": "Teilen Sie Ihre Visumerfahrungen und Fragen mit anderen Benutzern",
    "discussions.comingSoon": "Diskussionsforum kommt bald",
    "discussions.stayTuned": "Bleiben Sie dran für Updates!",
    
    // Actions (German translations)
    "actions.title": "Was können wir tun?",
    "actions.subtitle": "Gemeinsame Aktionen für faire Visapolitik",
    "actions.disclaimer.title": "Wichtige Notiz",
    "actions.disclaimer.text": "Die Vorschläge unten sind gemeinnützige und rechtliche Wege, um für Veränderungen zu kämpfen. Stellen Sie sicher, dass Ihre Handlungen lokalen Gesetzen entsprechen.",
    
    "actions.diaspora.title": "Engage with Turkish Diaspora",
    "actions.diaspora.description": "Leverage the influence of Turkish communities abroad",
    "actions.diaspora.point1": "Contact Turkish citizens living abroad to raise awareness with their local representatives",
    "actions.diaspora.point2": "Organize peaceful demonstrations in countries where Turkish communities are present",
    "actions.diaspora.point3": "Create petitions through diaspora organizations",
    
    "actions.tourism.title": "Alternative Tourism",
    "actions.tourism.description": "Consider alternative destinations for tourism and business",
    "actions.tourism.point1": "Explore visa-free countries or those with easier visa processes",
    "actions.tourism.point2": "Support countries that maintain fair visa policies for Turkish citizens",
    "actions.tourism.point3": "Share positive experiences from alternative destinations",
    
    "actions.awareness.title": "Farkındalık Yaratın",
    "actions.awareness.description": "Bilgi ve deneyimleri paylaşın",
    "actions.awareness.point1": "Vize ret hikayelerini sosyal medyada belgelendirin ve paylaşın",
    "actions.awareness.point2": "Vize sorunlarını ele almaları için gazeteciler ve medya kuruluşlarıyla iletişime geçin",
    "actions.awareness.point3": "Ailelere ve işletmelere etkisini vurgulayan içerikler oluşturun",
    
    "actions.legal.title": "Hukuki Savunuculuk",
    "actions.legal.description": "Adil muamele için yasal girişimleri destekleyin",
    "actions.legal.point1": "Ayrımcı vize uygulamalarına karşı çıkan organizasyonları destekleyin",
    "actions.legal.point2": "Olası yasal işlemler için haksız muamele vakalarını belgeleyin",
    "actions.legal.point3": "Yasal kanallar aracılığıyla karşılıklı vize politikalarını savunun",
    
    "actions.alternatives.title": "Alternatif Destinasyonlar",
    "actions.alternatives.description": "Türk vatandaşları için daha uygun vize politikaları olan bu ülkeleri değerlendirin:",
    
    "actions.contact.title": "Katılın",
    "actions.contact.description": "Bu girişime katkıda bulunmak ister misiniz? Fikir ve önerileriniz için bizimle iletişime geçin.",
    "actions.contact.email": "Bize e-posta gönderin",

    "countries.germany": "Deutschland",
    "countries.france": "Frankreich",
    "countries.italy": "Italien",
    "countries.spain": "Spanien",
    "countries.austria": "Österreich",
    "countries.belgium": "Belgien",
    "countries.denmark": "Dänemark",
    "countries.finland": "Finnland",
    "countries.greece": "Griechenland",
    "countries.netherlands": "Niederlande",
    "countries.portugal": "Portugal",
    "countries.sweden": "Schweden",
  },
};

export const LanguageProvider: React.FC<{children: React.ReactNode}> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // Try to get the language from localStorage or use 'tr' as default
    const savedLanguage = localStorage.getItem('language') as Language;
    return savedLanguage || 'tr';
  });

  useEffect(() => {
    // Save the language preference to localStorage
    localStorage.setItem('language', language);
    // Set the html lang attribute for accessibility
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
