// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xptezpotlgvxkanvbctd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwdGV6cG90bGd2eGthbnZiY3RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MjI3OTgsImV4cCI6MjA1OTE5ODc5OH0.rtrgsx4W52PmCuluNmat2jZfRgDIhmoKdEol6TJR0t0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);